# Generated by Django 5.1.4 on 2025-10-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
