# Generated by Django 5.1.4 on 2025-11-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0009_balancekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emi_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
