# Generated by Django 5.1.4 on 2025-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0010_customer_emi_per_month_customer_mobile_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paid_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='remaining_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
