# Generated by Django 5.1.4 on 2026-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0011_customer_paid_months_customer_remaining_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_1', models.CharField(max_length=255, unique=True)),
                ('fcm_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
