# Generated by Django 6.0.3 on 2026-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0012_fcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
