# Generated by Django 6.0.3 on 2026-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0013_device_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='secret',
        ),
        migrations.AddField(
            model_name='device',
            name='unlock_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
