# Generated by Django 6.0.3 on 2026-03-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0014_remove_device_secret_device_unlock_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dealer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
