# Generated by Django 6.0.3 on 2026-04-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0016_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('apk_url', models.URLField()),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
