# Generated by Django 6.0.3 on 2026-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0017_mdmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paid_down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
