# Generated by Django 6.0.3 on 2026-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0018_customer_paid_down_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdmconfig',
            name='name',
        ),
    ]
