# Generated by Django 6.0.3 on 2026-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0019_remove_mdmconfig_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdmconfig',
            name='apk_url',
        ),
        migrations.RemoveField(
            model_name='mdmconfig',
            name='checksum',
        ),
        migrations.AddField(
            model_name='mdmconfig',
            name='enrollment_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
