# Generated by Django 6.0.3 on 2026-04-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0020_remove_mdmconfig_apk_url_remove_mdmconfig_checksum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdmconfig',
            name='enrollment_data',
        ),
        migrations.AddField(
            model_name='customer',
            name='device_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mdmconfig',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='mdm_qr/'),
        ),
    ]
