# Generated by Django 6.0.3 on 2026-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0021_remove_mdmconfig_enrollment_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device_token',
        ),
        migrations.AddField(
            model_name='device',
            name='device_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
