# Generated by Django 6.0.3 on 2026-04-08 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0027_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
