# Generated by Django 6.0.3 on 2026-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0028_alter_device_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
