# Generated by Django 6.0.3 on 2026-04-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0030_servicerequest_alter_policy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='mobile',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
