# Generated by Django 6.0.3 on 2026-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0031_remove_servicerequest_mobile_servicerequest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdmconfig',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='mdmconfig',
            name='name',
            field=models.CharField(default='Default Config', max_length=100),
        ),
        migrations.AddField(
            model_name='mdmconfig',
            name='qr_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
