# Generated by Django 6.0.3 on 2026-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0032_remove_mdmconfig_qr_image_mdmconfig_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=20)),
                ('version_code', models.IntegerField()),
                ('apk_file', models.FileField(upload_to='apk/')),
                ('force_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
