# Generated by Django 6.0.3 on 2026-04-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0033_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
