# Generated by Django 6.0.3 on 2026-04-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emiapp', '0034_appversion_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='apk_file',
        ),
        migrations.AddField(
            model_name='appversion',
            name='apk_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
